float Physic_MaxSpeedMod()
{
	return 1;
}

float Physic_JumpVelocityFactor()
{
	return 1;
}

void Physic_CheckGroundHook()
{
}

void Physic_CheckWaterJumpHook()
{
}

float Physic_CanUseJetPack()
{
	return 0;
}

float Physic_JetPackVelocityFactor(float fvel)
{
	return 1;
}

void Physic_JetPackHook(float fuel_fact)
{
}

void Physic_OnJumpHook()
{
}

void Physic_LandingHook()
{
}

void Physic_FrameBeginHook()
{
}

void Physic_FrameEndHook()
{
}
