.void(entity e) drawGUI;
.entity frameGUI;
#define draw drawGUI
#define frame frameGUI
#define conwidth CVAR(vid_conwidth)
#define conheight CVAR(vid_conheight)
#include "../client-menu/classes/item.c"
#include "../client-menu/classes/container.c"
#include "../client-menu/classes/inputcontainer.c"
#include "../client-menu/classes/nexposee.c"
#include "../client-menu/classes/modalcontroller.c"
#include "../client-menu/classes/image.c"
#include "../client-menu/classes/label.c"
#include "../client-menu/classes/button.c"
#include "../client-menu/classes/checkbox.c"
#include "../client-menu/classes/radiobutton.c"
#include "../client-menu/classes/borderimage.c"
#include "../client-menu/classes/slider.c"
#include "../client-menu/classes/dialog.c"
#include "../client-menu/classes/tab.c"
#include "../client-menu/classes/textslider.c"
#include "../client-menu/classes/listbox.c"
#include "../client-menu/classes/inputbox.c"
#include "../client-menu/classes/nexuiz/dialog.c"
#include "classes/nexuiz/rootdialog.c"
#include "../client-menu/classes/nexuiz/button.c"
#include "../client-menu/classes/nexuiz/commandbutton.c"
#include "../client-menu/classes/nexuiz/bigcommandbutton.c"
#include "../client-menu/classes/nexuiz/dialog_teamselect.c"
#include "../client-menu/classes/nexuiz/slider.c"
#include "../client-menu/classes/nexuiz/textslider.c"
#include "../client-menu/classes/nexuiz/textlabel.c"
#include "../client-menu/classes/nexuiz/listbox.c"
#include "../client-menu/classes/nexuiz/inputbox.c"
#include "../client-menu/classes/nexuiz/dialog_quit.c"
#include "../client-menu/classes/nexuiz/checkbox.c"
#include "classes/nexuiz/voteargslist.c"
#include "classes/nexuiz/votelist.c"
#include "classes/nexuiz/dialog_gamemenu.c"
#include "classes/nexuiz/dialog_gamesettings.c"
#include "classes/nexuiz/dialog_radio.c"
#include "classes/nexuiz/mainwindow.c"
#include "classes/nexuiz/dialog_vcall.c"
#include "../client-menu/classes/nexuiz/dialog_saveload.c"
#include "classes/nexuiz/dialog_hint.c"
#include "classes/nexuiz/reportplayerlist.c"
#include "classes/nexuiz/reporttypelist.c"
#include "classes/nexuiz/dialog_report.c"
#include "classes/nexuiz/mutelist.c"
#include "classes/nexuiz/dialog_mutelist.c"
#include "classes/nexuiz/recordlist.c"
#include "classes/nexuiz/dialog_recordlist.c"
#include "classes/nexuiz/dialog_hud.c"
#include "classes/nexuiz/hudlist.c"
#undef draw
#undef frame
#undef conwidth
#undef conheight
